blueprint:
  name: Zähler für offene Rollos (mit Label-Ausschluss)
  description: >-
    Erstellt einen Sensor, der die Anzahl der offenen Rollos zählt (Device Class = shutter).
    Rollos können über ein Label von der Zählung ausgeschlossen werden.
  domain: template
    source_url: https://github.com/TheRealSimon42/Dynamic_Auto_Bubble_Dashboard/tree/main/blueprints/Offene_Rollos.yaml

  input:
    sensor_name:
      name: Name des Sensors
      description: Gib den Namen für den neuen Zähler-Sensor ein.
      selector:
        text:
      default: "Offene Rollos"

    exclusion_label:
      name: Ausschluss-Label
      description: Wähle das Label aus, um Entitäten von der Zählung auszuschließen (z.B. 'no-dboard').
      selector:
        label:

# --- HIER WIRD DIE TEMPLATE-ENTITÄT ANHAND DEINER LOGIK DEFINIERT ---
sensor:
  - name: !input sensor_name
    unique_id: "{{ slugify(input('sensor_name')) }}_shutter_counter"
    icon: mdi:window-shutter-open
    state: >
      {% set exclude = label_entities(input('exclusion_label')) %}
      {{ states.cover
        | selectattr('attributes.device_class', 'eq', 'shutter')
        | selectattr('state','eq','open')
        | rejectattr('entity_id','in', exclude)
        | list
        | count }}
