blueprint:
  name: Zähler für eingeschaltete Lichter (mit Label-Ausschluss)
  description: >-
    Erstellt einen Sensor, der die Anzahl der eingeschalteten Lichter zählt.
    Lichter können über ein Label von der Zählung ausgeschlossen werden.
  domain: template
  source_url: https://raw.githubusercontent.com/TheRealSimon42/home_assistant_templates/main/blueprint_templates/On_Lights.yaml

  input:
    sensor_name:
      name: Name des Sensors
      description: Gib den Namen für den neuen Zähler-Sensor ein.
      selector:
        text:
      default: "Angeschaltete Lichter"

    exclusion_label:
      name: Ausschluss-Label
      description: Wähle das Label aus, um Lichter von der Zählung auszuschließen (z.B. 'no-dboard').
      selector:
        label:

# --- HIER WIRD DIE TEMPLATE-ENTITÄT ANHAND DEINER LOGIK DEFINIERT ---
sensor:
  - name: !input sensor_name
    unique_id: "{{ slugify(input('sensor_name')) }}_light_counter"
    icon: mdi:lightbulb-group
    state: >
      {% set exclude = label_entities(input('exclusion_label')) %}
      {{ states.light
        | selectattr('state','eq','on')
        | rejectattr('entity_id','in', exclude)
        | list
        | count }}
